# application properties for test
spring:
  creditinfo:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: "jdbc:mysql://localhost:3306/creditinfotest"
      username: "creditinfo"
      password: "creditinfo"
      hikari:
        connection-timeout: 5000
        validation-timeout: 1000
        minimum-idle: 5
        max-lifetime: 2400000
        maximum-pool-size: 20
  springbatch:
    datasource:
      driver-class-name: org.h2.Driver
      jdbc-url: "jdbc:h2:tcp://localhost/~/test"
      username: "sa"
      password: ""
      hikari:
        connection-timeout: 5000
        validation-timeout: 1000
        minimum-idle: 5
        max-lifetime: 2400000
        maximum-pool-size: 20
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#        default_batch_fetch_size: 100
#        dialect: org.hibernate.dialect.H2Dialect
#       show_sql option is print sql using system.out
#       show_sql: true

  #Quartz Properties
  quartz:
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          jdbc:
            # quartz jdbc initialize or not
            schema: always
          scheduler:
            skipUpdateCheck: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
          plugin:
            shutdownhook:
              class: org.quartz.plugins.management.ShutdownHookPlugin
              cleanShutdown: true
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: false
            dataSource: myDataSource
            misfireThreshold: 60000
            useProperties: true
          dataSource:
            myDataSource:
              provider: hikaricp
              driver: org.h2.Driver
              URL: jdbc:h2:tcp://localhost/~/test
              user: sa
              password:

#p6spy jpa logging level
decorator:
  datasource:
    p6spy:
      enable-logging: true